services:
  mongo-db:
    image: mongo:latest
    container_name: nexus-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nexususer
      MONGO_INITDB_ROOT_PASSWORD: nexuspassword
    networks:
      - nexus-network
  nexus-api:
    container_name: nexus-api
    image: nexus-api 
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb://nexususer:nexuspassword@mongo-db:27017/nexusdb?authSource=admin"
      JWT_SECRET: "bunu-kimse-bilmemeli-cok-gizli-12345"
    depends_on:
      - mongo-db
    networks:
      - nexus-network

  nexus-client:
    container_name: nexus-client
    image: nexus-client
    ports:
      - "4200:80"
    depends_on:
      - nexus-api
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge